-- liquibase formatted sql

-- changeset kurumi:1741813307141-1
CREATE TABLE user_global_statistics
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    wins               INTEGER                                 NOT NULL,
    losses             INTEGER                                 NOT NULL,
    draws              INTEGER                                 NOT NULL,
    summary_time_clear INTEGER                                 NOT NULL,
    xp                 INTEGER                                 NOT NULL,
    CONSTRAINT pk_user_global_statistics PRIMARY KEY (id)
);

-- changeset kurumi:1741813307141-2
ALTER TABLE users
    ADD global_statistic_id BIGINT;

-- changeset kurumi:1741813307141-3
ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_GLOBALSTATISTIC FOREIGN KEY (global_statistic_id) REFERENCES user_global_statistics (id);

-- changeset kurumi:1741813307141-4
ALTER TABLE user_global_statistics
    ADD CONSTRAINT FK_USER_GLOBAL_STATISTICS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
