-- liquibase formatted sql

-- changeset Tim:1742046462134-1
CREATE TABLE match_invites
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inviter_id          BIGINT                                  NOT NULL,
    invitee_id          BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    active_diff_seconds BIGINT                                  NOT NULL,
    CONSTRAINT pk_match_invites PRIMARY KEY (id)
);

-- changeset Tim:1742046462134-2
ALTER TABLE match_invites
    ADD CONSTRAINT FK_MATCH_INVITES_ON_INVITEE FOREIGN KEY (invitee_id) REFERENCES users (id);

-- changeset Tim:1742046462134-3
ALTER TABLE match_invites
    ADD CONSTRAINT FK_MATCH_INVITES_ON_INVITER FOREIGN KEY (inviter_id) REFERENCES users (id);

-- changeset Tim:1742046462134-4
ALTER TABLE match_invite
    DROP CONSTRAINT fk_match_invite_on_invitee;

-- changeset Tim:1742046462134-5
ALTER TABLE match_invite
    DROP CONSTRAINT fk_match_invite_on_inviter;

-- changeset Tim:1742046462134-6
DROP TABLE match_invite CASCADE;
