-- liquibase formatted sql

-- changeset Tim:1742238303355-1
CREATE TABLE room_retries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_number  INTEGER                                 NOT NULL,
    time         INTEGER                                 NOT NULL,
    completed_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    match_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_room_retries PRIMARY KEY (id)
);

-- changeset Tim:1742238303355-2
ALTER TABLE room_results
    ADD CONSTRAINT uk_room_user_match_no_retry UNIQUE (user_id, match_id);

-- changeset Tim:1742238303355-3
ALTER TABLE room_retries
    ADD CONSTRAINT FK_ROOM_RETRIES_ON_MATCH FOREIGN KEY (match_id) REFERENCES matches (id);

-- changeset Tim:1742238303355-4
ALTER TABLE room_retries
    ADD CONSTRAINT FK_ROOM_RETRIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset Tim:1742238303355-5
ALTER TABLE matches
    DROP COLUMN max_retries;
