-- liquibase formatted sql

-- changeset Tim:1742475256811-3
CREATE TABLE draft_actions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    draft_id          BIGINT                                  NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    action_type       VARCHAR(255)                            NOT NULL,
    character_name    VARCHAR(255),
    timestamp         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_timeout_action BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_draft_actions PRIMARY KEY (id)
);

-- changeset Tim:1742475256811-4
CREATE TABLE draft_banned_characters
(
    draft_id          BIGINT NOT NULL,
    banned_characters VARCHAR(255)
);

-- changeset Tim:1742475256811-5
CREATE TABLE draft_characters
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    element        VARCHAR(255)                            NOT NULL,
    level          INTEGER                                 NOT NULL,
    rarity         INTEGER                                 NOT NULL,
    constellations INTEGER                                 NOT NULL,
    CONSTRAINT pk_draft_characters PRIMARY KEY (id)
);

-- changeset Tim:1742475256811-6
CREATE TABLE draft_player1_available_characters
(
    character_id BIGINT NOT NULL,
    draft_id     BIGINT NOT NULL,
    CONSTRAINT pk_draft_player1_available_characters PRIMARY KEY (character_id, draft_id)
);

-- changeset Tim:1742475256811-7
CREATE TABLE draft_player1_characters
(
    draft_id          BIGINT NOT NULL,
    player1characters VARCHAR(255)
);

-- changeset Tim:1742475256811-8
CREATE TABLE draft_player2_available_characters
(
    character_id BIGINT NOT NULL,
    draft_id     BIGINT NOT NULL,
    CONSTRAINT pk_draft_player2_available_characters PRIMARY KEY (character_id, draft_id)
);

-- changeset Tim:1742475256811-9
CREATE TABLE draft_player2_characters
(
    draft_id          BIGINT NOT NULL,
    player2characters VARCHAR(255)
);

-- changeset Tim:1742475256811-10
CREATE TABLE match_drafts
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    current_state            VARCHAR(255)                            NOT NULL,
    current_state_start_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    current_step_index       INTEGER                                 NOT NULL,
    penalty_time_player1     INTEGER                                 NOT NULL,
    penalty_time_player2     INTEGER                                 NOT NULL,
    current_state_deadline   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_player1ready          BOOLEAN                                 NOT NULL,
    is_player2ready          BOOLEAN                                 NOT NULL,
    draft_schema_json        TEXT,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    match_id                 BIGINT                                  NOT NULL,
    CONSTRAINT pk_match_drafts PRIMARY KEY (id)
);

-- changeset Tim:1742475256811-11
ALTER TABLE draft_characters
    ADD CONSTRAINT uc_d269cc8e1bb91731143854178 UNIQUE (name, constellations, element, level, rarity);

-- changeset Tim:1742475256811-12
ALTER TABLE draft_player1_available_characters
    ADD CONSTRAINT uc_draft_player1_available_characters_character UNIQUE (character_id);

-- changeset Tim:1742475256811-13
ALTER TABLE draft_player2_available_characters
    ADD CONSTRAINT uc_draft_player2_available_characters_character UNIQUE (character_id);

-- changeset Tim:1742475256811-14
ALTER TABLE draft_actions
    ADD CONSTRAINT FK_DRAFT_ACTIONS_ON_DRAFT FOREIGN KEY (draft_id) REFERENCES match_drafts (id);

-- changeset Tim:1742475256811-15
ALTER TABLE draft_actions
    ADD CONSTRAINT FK_DRAFT_ACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset Tim:1742475256811-16
ALTER TABLE match_drafts
    ADD CONSTRAINT FK_MATCH_DRAFTS_ON_MATCH FOREIGN KEY (match_id) REFERENCES matches (id);

-- changeset Tim:1742475256811-17
ALTER TABLE draft_banned_characters
    ADD CONSTRAINT fk_draft_banned_characters_on_match_draft FOREIGN KEY (draft_id) REFERENCES match_drafts (id);

-- changeset Tim:1742475256811-18
ALTER TABLE draft_player1_characters
    ADD CONSTRAINT fk_draft_player1_characters_on_match_draft FOREIGN KEY (draft_id) REFERENCES match_drafts (id);

-- changeset Tim:1742475256811-19
ALTER TABLE draft_player2_characters
    ADD CONSTRAINT fk_draft_player2_characters_on_match_draft FOREIGN KEY (draft_id) REFERENCES match_drafts (id);

-- changeset Tim:1742475256811-20
ALTER TABLE draft_player2_available_characters
    ADD CONSTRAINT fk_draplaavacha_on_draft_character FOREIGN KEY (character_id) REFERENCES draft_characters (id);

-- changeset Tim:1742475256811-21
ALTER TABLE draft_player1_available_characters
    ADD CONSTRAINT "fk_draplaavacha_on_draft_characteralHVWq" FOREIGN KEY (character_id) REFERENCES draft_characters (id);

-- changeset Tim:1742475256811-22
ALTER TABLE draft_player2_available_characters
    ADD CONSTRAINT fk_draplaavacha_on_match_draft FOREIGN KEY (draft_id) REFERENCES match_drafts (id);

-- changeset Tim:1742475256811-23
ALTER TABLE draft_player1_available_characters
    ADD CONSTRAINT "fk_draplaavacha_on_match_draftcsZOCY" FOREIGN KEY (draft_id) REFERENCES match_drafts (id);
