-- liquibase formatted sql

-- changeset intezya:1743912772974-3
CREATE TABLE ban_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, banned_by BIGINT, reason VARCHAR(255), created_at TIMESTAMP WITHOUT TIME ZONE, dispute_approved BOOLEAN, CONSTRAINT pk_ban_history PRIMARY KEY (id));

-- changeset intezya:1743912772974-4
ALTER TABLE users ADD ban_reason VARCHAR(255);

-- changeset intezya:1743912772974-7
ALTER TABLE ban_history ADD CONSTRAINT FK_BAN_HISTORY_ON_BANNED_BY FOREIGN KEY (banned_by) REFERENCES users (id);

-- changeset intezya:1743912772974-8
ALTER TABLE ban_history ADD CONSTRAINT FK_BAN_HISTORY_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
