-- liquibase formatted sql

-- changeset Tim:1740488002270-1
CREATE TABLE game_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    collection VARCHAR(255),
    type       SMALLINT,
    rarity     SMALLINT,
    CONSTRAINT pk_game_items PRIMARY KEY (id)
);

-- changeset Tim:1740488002270-2
CREATE TABLE trades
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id BIGINT                                  NOT NULL,
    receiver_id  BIGINT                                  NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_trades PRIMARY KEY (id)
);

-- changeset Tim:1740488002270-3
CREATE TABLE user_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    item_id     BIGINT                                  NOT NULL,
    trade_id    BIGINT                                  NOT NULL,
    source_type VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_user_items PRIMARY KEY (id)
);

-- changeset Tim:1740488002270-4
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255)                            NOT NULL,
    hwid       VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Tim:1740488002270-5
ALTER TABLE users
    ADD CONSTRAINT uc_users_hwid UNIQUE (hwid);

-- changeset Tim:1740488002270-6
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset Tim:1740488002270-7
ALTER TABLE trades
    ADD CONSTRAINT FK_TRADES_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id);

-- changeset Tim:1740488002270-8
ALTER TABLE trades
    ADD CONSTRAINT FK_TRADES_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES users (id);

-- changeset Tim:1740488002270-9
ALTER TABLE user_items
    ADD CONSTRAINT FK_USER_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES game_items (id);

-- changeset Tim:1740488002270-10
ALTER TABLE user_items
    ADD CONSTRAINT FK_USER_ITEMS_ON_TRADE FOREIGN KEY (trade_id) REFERENCES trades (id);

-- changeset Tim:1740488002270-11
ALTER TABLE user_items
    ADD CONSTRAINT FK_USER_ITEMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
